# Generated by Django 3.1.6 on 2021-02-04 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.CharField(max_length=50)),
                ('picture_set', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('internet_name', models.CharField(max_length=50)),
                ('real_name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_id', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('T1', 'Short set of text; max 100 characters'), ('T2', 'Medium text; max 500 characters'), ('T3', 'Long text; no limit'), ('IM', 'Image'), ('VD', 'Video')], default='T1', max_length=2)),
                ('url', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=10000)),
                ('legal_status', models.CharField(choices=[('AG', 'No legal issues with this post'), ('DM', 'Copyright issues'), ('IS', 'Illegal speech')], default='AG', max_length=2)),
                ('expanded_legal_status', models.CharField(max_length=50)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shark.shark')),
            ],
        ),
    ]
