# Generated by Django 3.1.6 on 2021-02-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooth',
            name='file_url',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tooth',
            name='type',
            field=models.CharField(choices=[('T1', 'Short set of text; max 100 characters'), ('T2', 'Medium text; max 500 characters'), ('T3', 'Long text; no limit'), ('IM', 'Image'), ('VD', 'Video'), ('LK', 'Link')], default='T1', max_length=2),
        ),
    ]
