# Generated by Django 3.1.6 on 2021-02-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shark', '0002_auto_20210223_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooth',
            name='author_id',
            field=models.CharField(max_length=50),
        ),
    ]
