# Generated by Django 3.1.6 on 2021-03-06 12:55

from django.db import migrations, models
import shark.models


class Migration(migrations.Migration):

    dependencies = [
        ('shark', '0003_auto_20210225_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userID', models.CharField(max_length=30, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('birthdate', models.DateField(verbose_name='Birth Date')),
                ('email', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', shark.models.SiteUserManager()),
            ],
        ),
    ]
