# Generated by Django 3.1.6 on 2021-03-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shark', '0004_siteuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='email',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
