# Generated by Django 3.1.6 on 2021-03-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shark', '0006_remove_siteuser_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
