# Generated by Django 3.1.6 on 2021-05-23 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shark', '0010_auto_20210324_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=50, null=True)),
                ('legal_status', models.CharField(choices=[('AG', 'No legal issues with this post'), ('DM', 'Copyright issues'), ('IS', 'Illegal speech')], default='AG', max_length=2)),
                ('expanded_legal_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Shark',
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('squeal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shark.squeal')),
                ('type', models.CharField(choices=[('L', 'Like'), ('D', 'Dislike'), ('H', 'Happy'), ('S', 'Sad'), ('M', 'Mad'), ('X', 'Dismiss as inappropriate')], max_length=1)),
            ],
            bases=('shark.squeal',),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('squeal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shark.squeal')),
                ('url', models.CharField(max_length=150)),
            ],
            bases=('shark.squeal',),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('squeal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shark.squeal')),
                ('full_text', models.CharField(max_length=10000, null=True)),
                ('length', models.IntegerField(max_length=5)),
                ('type', models.CharField(choices=[('S', 'Short text, <100 characters'), ('M', 'Medium text, >100 & <600 characters'), ('L', 'Long text, >600 characters')], max_length=1)),
            ],
            bases=('shark.squeal',),
        ),
        migrations.DeleteModel(
            name='Tooth',
        ),
        migrations.AddField(
            model_name='squeal',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squeal',
            name='parents',
            field=models.ManyToManyField(null=True, related_name='_squeal_parents_+', to='shark.Squeal'),
        ),
    ]
