# Generated by Django 3.1.6 on 2021-05-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shark', '0011_auto_20210523_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squeal',
            name='parents',
            field=models.ManyToManyField(related_name='_squeal_parents_+', to='shark.Squeal'),
        ),
        migrations.AlterField(
            model_name='text',
            name='length',
            field=models.IntegerField(),
        ),
    ]
